{
 "title": "X-Manager Live",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "label_values(application)" },
   { "name": "xmService", "query": "label_values(xmService)" }
  ]
 },
 "panels": [
  { "title": "Last success", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$xmService",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 1 },
   "repeat": "xmService",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-xm_last_hit_success_seconds{application=\"$application\",xmService=\"$xmService\"}",
     "legendFormat": "success"
    },
    {
     "expr": "time()-xm_last_hit_error_seconds{application=\"$application\",xmService=\"$xmService\"}",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "$xmService",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-xm_last_hit_success_seconds{application=\"$application\",xmService=\"$xmService\"}",
     "legendFormat": "success"
    },
    {
     "expr": "time()-xm_last_hit_error_seconds{application=\"$application\",xmService=\"$xmService\"}",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "$xmService",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-xm_last_hit_success_seconds{application=\"$application\",xmService=\"$xmService\"}",
     "legendFormat": "success"
    },
    {
     "expr": "time()-xm_last_hit_error_seconds{application=\"$application\",xmService=\"$xmService\"}",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "$xmService",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-xm_last_hit_success_seconds{application=\"$application\",xmService=\"$xmService\"}",
     "legendFormat": "success"
    },
    {
     "expr": "time()-xm_last_hit_error_seconds{application=\"$application\",xmService=\"$xmService\"}",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "$xmService",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-xm_last_hit_success_seconds{application=\"$application\",xmService=\"$xmService\"}",
     "legendFormat": "success"
    },
    {
     "expr": "time()-xm_last_hit_error_seconds{application=\"$application\",xmService=\"$xmService\"}",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "$xmService",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-xm_last_hit_success_seconds{application=\"$application\",xmService=\"$xmService\"}",
     "legendFormat": "success"
    },
    {
     "expr": "time()-xm_last_hit_error_seconds{application=\"$application\",xmService=\"$xmService\"}",
     "legendFormat": "error"
    }
   ]
  },
  { "title": "Hits", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "$xmService hits",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "repeat": "xmService",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(xm_hit_fail_total{application=\"$application\",xmService=~\"xmService\"}[$__rate_interval]))",
     "legendFormat": "failed"
    },
    {
     "expr": "sum(increase(xm_hit_success_total{application=\"$application\",xmService=~\"$xmService\"}[$__rate_interval]))",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "$xmService hits",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(xm_hit_fail_total{application=\"$application\",xmService=~\"xmService\"}[$__rate_interval]))",
     "legendFormat": "failed"
    },
    {
     "expr": "sum(increase(xm_hit_success_total{application=\"$application\",xmService=~\"$xmService\"}[$__rate_interval]))",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "$xmService hits",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(xm_hit_fail_total{application=\"$application\",xmService=~\"xmService\"}[$__rate_interval]))",
     "legendFormat": "failed"
    },
    {
     "expr": "sum(increase(xm_hit_success_total{application=\"$application\",xmService=~\"$xmService\"}[$__rate_interval]))",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "$xmService hits",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(xm_hit_fail_total{application=\"$application\",xmService=~\"xmService\"}[$__rate_interval]))",
     "legendFormat": "failed"
    },
    {
     "expr": "sum(increase(xm_hit_success_total{application=\"$application\",xmService=~\"$xmService\"}[$__rate_interval]))",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "$xmService hits",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(xm_hit_fail_total{application=\"$application\",xmService=~\"xmService\"}[$__rate_interval]))",
     "legendFormat": "failed"
    },
    {
     "expr": "sum(increase(xm_hit_success_total{application=\"$application\",xmService=~\"$xmService\"}[$__rate_interval]))",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "$xmService hits",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(xm_hit_fail_total{application=\"$application\",xmService=~\"xmService\"}[$__rate_interval]))",
     "legendFormat": "failed"
    },
    {
     "expr": "sum(increase(xm_hit_success_total{application=\"$application\",xmService=~\"$xmService\"}[$__rate_interval]))",
     "legendFormat": "success"
    }
   ]
  },
  { "title": "All services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Hits /day",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (xmService)(increase(xm_hit_success_total{application=\"$application\"}[1d]))",
     "legendFormat": "{{xmService}}"
    },
    {
     "expr": "sum (increase(xm_hit_success_total{application=\"$application\"}[1d]))",
     "legendFormat": "all"
    }
   ]
  }
 ]
}